["0.1"]
julia = "0.4-0.7"

["0.1-0.2"]
ODE = "0.1-1.0"

["0.1-0.3"]
Distributions = "0.1-0.15"
JLD = "0.5-0.8"
JSON = "0.1-0.16"

["0.2-0.3"]
julia = "0.5-0.7"

["0.3"]
DifferentialEquations = "1.5-4.0"
