["0.0-0.3"]
julia = "0.5-0.7"
DiffEqBase = "0.0-2.10"
DiffEqJump = "0.0-1.0"

["0.2-1.0"]
Compat = "0.17-0.49"

["0.3-1.0"]
DataStructures = "0.4.6-0.7"

["1.0"]
julia = "0.6-0.7"
DiffEqBase = "3.0"
DiffEqJump = "1.0"
