["0.0"]
NLsolve = "0.1-0.13"

["0.0-0.3"]
julia = "0.4"
DiffEqBase = "0.0-2.10"
IterativeSolvers = "0.0-0.4"
OrdinaryDiffEq = "0.0-2.37"
Plots = "0.0-0.15"

["0.0.1"]
Atom = "0.1-0.6"

["0.0.1-0.0.2"]
LaTeXStrings = "0.1-0.3"
PyPlot = "1.0-2.3"

["0.0.2-0.3"]
Parameters = "0.0-0.8"

["0.0.3"]
ForwardDiff = "0.0-0.7"
JLD = "0.5-0.8"

["0.0.3-0.3"]
ChunkedArrays = "0.0-0.1"
EllipsisNotation = "0.0-0.3"
GrowableArrays = "0.0"

["0.1.2-0.3"]
GenericSVD = "0.0-0.1"

["0.1.4-0.3"]
ForwardDiff = "0.0-0.7"

["0.3"]
Compat = "0.0-0.49"
InplaceOps = "0.0-0.1"

["0.4"]
SIUnits = "0.0.6-0.1"

["0.4-0.5"]
ChunkedArrays = "0.0.2-0.1"
Compat = "0.8.8-0.49"
ForwardDiff = "0.2.4-0.7"
GenericSVD = "0.0.2-0.1"
InplaceOps = "0.0.5-0.1"
IterativeSolvers = "0.2.2-0.4"
Plots = "0.9.2-0.15"

["0.4-1.0"]
DiffEqBase = "0.0-0.14"
OrdinaryDiffEq = "0.0-1.1"
StochasticDiffEq = "0.0-0.5"

["0.4-2.2"]
julia = "0.5-0.7"

["0.4.0"]
Parameters = "0.3.1-0.8"

["0.4.1-0.5"]
Parameters = "0.5-0.8"

["0.5"]
NLsolve = "0.7.3-0.13"
Ranges = "0.0"
Sundials = "0.3-1.1"

["1.0"]
AlgebraicDiffEq = "0.0-0.1"
DiffEqDevTools = "0.0-1.0"
DiffEqParamEstim = "0.0-1.0"
DiffEqSensitivity = "0.0-1.0"
FiniteElementDiffEq = "0.0-0.5"
Reexport = "0.0-0.1"
StokesDiffEq = "0.0-0.2"
Sundials = "0.1-1.1"

["1.1"]
DiffEqBase = "0.1.3-0.14"
DiffEqDevTools = "0.1.1-1.0"
OrdinaryDiffEq = "0.1.1-1.1"
StochasticDiffEq = "0.0.5-0.5"
Sundials = "0.3-1.1"

["1.1-1.10"]
AlgebraicDiffEq = "0.0.2-0.1"
DiffEqParamEstim = "0.0.2-1.0"
DiffEqSensitivity = "0.0.2-1.0"
FiniteElementDiffEq = "0.0.5-0.5"
ParameterizedFunctions = "0.3.2-3.0"
StokesDiffEq = "0.0.2-0.2"

["1.1-4.0"]
Reexport = "0.0.3-0.1"

["1.2-1.4"]
DiffEqProblemLibrary = "0.2-1.0"

["1.2-1.6"]
DiffEqBase = "0.2-0.14"
OrdinaryDiffEq = "0.2-1.1"
StochasticDiffEq = "0.1-0.5"

["1.2-1.10"]
DiffEqDevTools = "0.2-1.0"
Sundials = "0.5-1.1"

["1.5-1.10"]
DiffEqPDEBase = "0.0-0.4"

["1.6"]
DelayDiffEq = "0.0-2.0"

["1.6-1.10"]
DiffEqCallbacks = "0.0-1.0"
DiffEqMonteCarlo = "0.0-0.10"

["1.7-1.9"]
DiffEqBase = "0.8-0.14"

["1.7-1.10"]
DelayDiffEq = "0.1-2.0"
OrdinaryDiffEq = "1.2-2.37"
StochasticDiffEq = "1.0-3.0"

["1.8-1.10"]
DiffEqFinancial = "0.0-1.0"
DiffEqJump = "0.0-1.0"
MultiScaleArrays = "0.0-0.6"

["1.8-3.1"]
DiffEqBiological = "0.0-1.0"

["1.9.0"]
PyDSTool = "0.0-0.2"

["1.10"]
DiffEqBase = "0.15-2.10"

["2.0-2.1"]
ParameterizedFunctions = "1.3-3.0"
PyDSTool = "0.1.2-0.2"

["2.0-2.2"]
OrdinaryDiffEq = "2.0-2.37"
StochasticDiffEq = "2.0-3.0"

["2.0-3.1"]
AlgebraicDiffEq = "0.1"
DelayDiffEq = "0.3-2.0"
DiffEqBase = "1.0-2.10"
DiffEqCallbacks = "0.0.2-1.0"
DiffEqDevTools = "0.8-1.0"
DiffEqFinancial = "0.2-1.0"
DiffEqJump = "0.3-1.0"
DiffEqMonteCarlo = "0.3-0.10"
DiffEqNoiseProcess = "0.0-1.0"
DiffEqParamEstim = "0.3-1.0"
DiffEqPDEBase = "0.3-0.4"
DiffEqSensitivity = "0.2-1.0"
FiniteElementDiffEq = "0.3-0.5"
MultiScaleArrays = "0.1-0.6"
RecursiveArrayTools = "0.4.1-0.14"
SteadyStateDiffEq = "0.0-0.2"
Sundials = "0.11-1.1"

["2.0-4.0"]
DimensionalPlotRecipes = "0.0.2"

["2.1-3.1"]
DiffEqUncertainty = "0.0-0.1"

["2.2-3.1"]
ParameterizedFunctions = "2.0-3.0"

["2.3-3.1"]
OrdinaryDiffEq = "2.11-2.37"
StochasticDiffEq = "2.11.1-3.0"

["2.3-4.0"]
julia = "0.6-0.7"

["3.0-3.1"]
BoundaryValueDiffEq = "0.0-1.0"
DiffEqPhysics = "0.0-1.0"

["4.0"]
BoundaryValueDiffEq = "1.0"
DelayDiffEq = "2.0"
DiffEqBase = "3.0"
DiffEqBiological = "1.0"
DiffEqCallbacks = "1.0"
DiffEqDevTools = "1.0"
DiffEqFinancial = "1.0"
DiffEqJump = "1.0"
DiffEqMonteCarlo = "0.10"
DiffEqNoiseProcess = "1.0"
DiffEqParamEstim = "1.0"
DiffEqPDEBase = "0.4"
DiffEqPhysics = "1.0"
DiffEqSensitivity = "1.0"
DiffEqUncertainty = "0.1"
MultiScaleArrays = "0.5-0.6"
OrdinaryDiffEq = "3.0"
ParameterizedFunctions = "3.0"
RecursiveArrayTools = "0.14"
SteadyStateDiffEq = "0.2"
StochasticDiffEq = "3.0"
Sundials = "1.0-1.1"
