["0.1-0.8"]
julia = "0.4-0.7"

["0.1-0.10"]
Cairo = "0.0-0.4"
Colors = "0.4-0.8"

["0.2-0.10"]
Compat = "0.9.1-0.49"

["0.6"]
BaseTestNext = "0.1-0.2"

["0.7-0.10"]
FileIO = "0.0-0.6"

["0.8.5-0.10"]
Hiccup = "0.0-0.1"
Juno = "0.1-0.4"

["0.9"]
julia = "0.5-0.7"

["0.10"]
julia = "0.6-0.7"
ImageMagick = "0.0-0.5"
