version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels:
      - "automerge"
      - "dependencies"
      - "github-actions"
