["0.1"]
DynamicalSystemsBase = "0.1"

["0.1-0.4"]
julia = "0.6-0.7"
Combinatorics = "0.0-0.5"
Distances = "0.1-0.5"
ForwardDiff = "0.5-0.7"
IterTools = "0.1-0.2"
LsqFit = "0.3"
NearestNeighbors = "0.1-0.3"
Reexport = "0.0-0.1"
Requires = "0.4.3"
StaticArrays = "0.5-0.6"
StatsBase = "0.8.2-0.19"

["0.1-0.4.2"]
OrdinaryDiffEq = "2.17-2.37"

["0.2"]
DynamicalSystemsBase = "0.2.0"

["0.3"]
DynamicalSystemsBase = "0.2.1"

["0.4.0"]
DynamicalSystemsBase = "0.3.1-0.3.3"

["0.4.1-0.4.2"]
DynamicalSystemsBase = "0.4"

["0.4.3"]
DynamicalSystemsBase = "0.4.1"
OrdinaryDiffEq = "2.17-3.0"
