["0.0"]
julia = "0.6-0.7"
Atom = "0.6.6-0.6.7"
Blink = "0.6"
ColorBrewer = "0.3.1"
DataFrames = "0.11.5"
Distributions = "0.15"
JSON = "0.16.4"
Juno = "0.3.2-0.4"
KernelDensity = "0.4"
Missings = "0.2.4-0.2.5"
NoveltyColors = "0.3"
Parameters = "0.8.1"
StatsBase = "0.19.5"
