["0.0"]
DiffEqBase = "0.0-0.14"

["0.0-0.5"]
julia = "0.5-0.7"

["0.0.2"]
Compat = "0.0-0.49"

["0.1-0.2"]
DiffEqBase = "0.15-2.10"

["0.2-1.0"]
Compat = "0.17-0.49"

["0.3-0.5"]
DiffEqBase = "1.5.1-2.10"

["0.4-1.0"]
Reexport = "0.0-0.1"

["1.0"]
julia = "0.6-0.7"
DiffEqBase = "3.0"
