["0.0-0.1"]
DiffEqBase = "0.0-2.10"

["0.0.1-0.0.3"]
julia = "0.2-0.7"

["0.0.4"]
julia = "0.3-0.7"

["0.1"]
julia = "0.4-0.7"

["0.1-1.0"]
FactCheck = "0.0-0.4"

["0.2-0.3"]
julia = "0.5-0.7"
DiffEqBase = "0.15-2.10"

["0.3-1.0"]
Reexport = "0.0-0.1"

["1.0"]
julia = "0.6-0.7"
DiffEqBase = "3.0"
