["0.0"]
DiffEqBase = "1.0-1.2"

["0.0-0.2"]
julia = "0.5-0.7"

["0.0-0.4"]
ResettableStacks = "0.0-0.3"

["0.0-1.0"]
DataStructures = "0.2-0.7"
RecipesBase = "0.0-0.3"
RecursiveArrayTools = "0.0-0.14"

["0.1-0.2"]
DiffEqBase = "1.3.1-2.10"

["0.3-0.8"]
DiffEqBase = "1.13-2.10"

["0.3-1.0"]
julia = "0.6-0.7"
RandomNumbers = "0.0-0.1"

["0.5-1.0"]
ResettableStacks = "0.2-0.3"

["0.8-1.0"]
StaticArrays = "0.0-0.6"

["1.0"]
DiffEqBase = "3.0"
