["0.0"]
julia = "0.4-0.7"
Ipopt = "0.1-0.2"

["0.0-0.1"]
ODE = "0.1-1.0"

["0.0-0.2"]
DiffEqBase = "0.0-2.10"
MathProgBase = "0.1-0.7"
OrdinaryDiffEq = "0.0-2.37"

["0.1"]
julia = "0.5-0.7"

["0.2"]
julia = "0.6-0.7"
Ipopt = "0.1-0.2"
