["0.0"]
Catalan = "0.0"

["0.0-0.1"]
julia = "0.3-0.7"

["0.0-0.2"]
OrdinaryDiffEq = "0.0-2.37"

["0.0-0.2.0"]
Distributions = "0.1-0.15"
ODE = "0.1-1.0"

["0.1"]
Combinatorics = "0.0-0.5"

["0.2"]
julia = "0.4-0.7"

["0.2-0.3"]
Combinatorics = "0.2-0.5"

["0.2.0"]
Docile = "0.0-0.5"

["0.2.1"]
Compat = "0.9.2-0.49"
ODE = "0.2.1-1.0"

["0.2.1-0.3"]
Distributions = "0.8.10-0.15"
GSL = "0.3.1-0.3.6"

["0.3"]
julia = "0.6-0.7"
OrdinaryDiffEq = "2.19.1-2.37"
