["0.1"]
julia = "0.3-0.7"
Requires = "0.1-0.4"

["0.1-0.2"]
Sundials = "0.1-1.1"

["0.2"]
julia = "0.5-0.7"
Documenter = "0.1-0.13"
Ipopt = "0.1-0.2"
JuMP = "0.1-0.18"
Plots = "0.0-0.15"
ReactiveBasics = "0.0-0.2"
