["0.1-0.3"]
julia = "0.6-0.7"
Documenter = "0.1-0.13"
NetCDF = "0.1-0.6"
WriteVTK = "0.0-0.6"

["0.2"]
Homebrew = "0.0.4-0.6"
WinRPM = "0.1-0.3"

["0.2-0.3.0"]
Compat = "0.9.1-0.49"

["0.2.0"]
BinDeps = "0.2.12-0.8"

["0.2.1"]
BinDeps = "0.3-0.8"

["0.3.1"]
Compat = "0.42-0.49"
