["0.1-0.4"]
julia = "0.4-0.7"

["0.1-0.5.2"]
Lazy = "0.1-0.12"

["0.1-0.6"]
CodeTools = "0.1-0.4"
Hiccup = "0.0-0.1"
JSON = "0.1-0.16"
LNR = "0.0"
Media = "0.1-0.3"

["0.3-0.6"]
Blink = "0.1-0.6"
Reexport = "0.0-0.1"

["0.4.1-0.5.2"]
Requires = "0.1-0.4"

["0.4.1-0.6"]
MacroTools = "0.1-0.4"

["0.5"]
julia = "0.5-0.7"

["0.5-0.6.0"]
ASTInterpreter = "0.0"
Gallium = "0.0-0.1"

["0.5.1-0.5.8"]
Juno = "0.1-0.4"

["0.5.3-0.6"]
Lazy = "0.11.3-0.12"

["0.5.9-0.6"]
Juno = "0.2.6-0.4"

["0.6"]
julia = "0.6-0.7"

["0.6.2-0.6.7"]
DocSeeker = "0.1"

["0.6.3-0.6.7"]
ASTInterpreter2 = "0.1"
