["0.0"]
OrdinaryDiffEq = "0.0-3.0"

["0.0-0.1"]
AlgebraicDiffEq = "0.0-0.1"
DiffEqBase = "0.0-0.14"
FiniteElementDiffEq = "0.0-0.5"
StochasticDiffEq = "0.0-3.0"

["0.0-0.3"]
ParameterizedFunctions = "0.2-3.0"

["0.0-0.8"]
JLD = "0.6.5-0.8"

["0.0-0.9"]
julia = "0.5-0.7"

["0.2"]
StochasticDiffEq = "0.1-3.0"

["0.2-0.3"]
AlgebraicDiffEq = "0.0.2-0.1"

["0.2-0.4"]
DiffEqBase = "0.2-0.14"
FiniteElementDiffEq = "0.0.5-0.5"

["0.4-0.5"]
ParameterizedFunctions = "0.5-3.0"

["0.4-1.0"]
DiffEqPDEBase = "0.0-0.4"

["0.5-0.9"]
DiffEqBase = "0.15-2.10"

["0.6-1.0"]
ParameterizedFunctions = "2.0-3.0"

["0.10-0.11"]
DiffEqBase = "1.21-2.10"

["0.10-1.0"]
julia = "0.6-0.7"

["1.0"]
DiffEqBase = "3.0.3-3.0.4"
