["0.0"]
julia = "0.5-0.7"

["0.0-0.1"]
BinDeps = "0.4-0.8"
Homebrew = "0.3-0.6"

["0.0.3-0.1"]
CMakeWrapper = "0.0-0.1"

["0.1"]
julia = "0.6-0.7"
BufferedStreams = "0.0-0.3"
Compat = "0.27-0.49"
StaticArrays = "0.0-0.6"
