["0.1"]
julia = "0.5-0.7"

["0.1-0.2.1"]
DataFlow = "0.1-0.2.0"
Iterators = "0.1-0.3"

["0.1-0.4"]
Juno = "0.1-0.4"

["0.2-0.4"]
julia = "0.6-0.7"
MacroTools = "0.3.3-0.4"

["0.2.2"]
DataFlow = "0.2.1"

["0.3-0.4"]
DataFlow = "0.2.1-0.3"
NNlib = "0.1-0.2"
Requires = "0.1-0.4"

["0.3-0.4.0"]
ForwardDiff = "0.0-0.7"

["0.4.1"]
Adapt = "0.1-0.2"
Colors = "0.4-0.8"
ForwardDiff = "0.5-0.7"
GZip = "0.1-0.3"
