["0.1"]
julia = "0.5-0.7"
DataArrays = "0.0-0.6"
DataFrames = "0.1-0.10"
DataTables = "0.0"
NullableArrays = "0.0-0.1"

["0.1-0.3"]
BinDeps = "0.0-0.8"
WinRPM = "0.1-0.3"

["0.2-0.3"]
julia = "0.6-0.7"
DataValues = "0.3"
