["0.0"]
DiffEqBase = "0.5-0.6"
OrdinaryDiffEq = "1.0-1.1"
RecursiveArrayTools = "0.1.2-0.14"

["0.0-0.4"]
julia = "0.5-0.7"

["0.0-0.10"]
Combinatorics = "0.0-0.5"

["0.0-1.6"]
DiffEqDiffTools = "0.0-0.2"

["0.0-2.0"]
DataStructures = "0.4.6-0.7"

["0.1"]
OrdinaryDiffEq = "1.2-2.14"

["0.1-0.2"]
DiffEqBase = "0.8-0.14"

["0.1-2.0"]
RecursiveArrayTools = "0.2-0.14"

["0.2-0.4"]
OrdinaryDiffEq = "1.6-2.14"

["0.3-0.5.0"]
DiffEqBase = "0.15-1.24"

["0.4-0.10"]
Compat = "0.17-0.49"

["0.5-2.0"]
julia = "0.6-0.7"
Reexport = "0.0-0.1"

["0.5.0"]
OrdinaryDiffEq = "2.9-2.14"

["0.5.1-0.5.2"]
DiffEqBase = "1.15-1.24"

["0.5.1-0.6"]
OrdinaryDiffEq = "2.10-2.14"

["0.6-0.9"]
DiffEqBase = "1.16-1.24"

["0.6-2.0"]
MuladdMacro = "0.0"

["0.7-0.8"]
OrdinaryDiffEq = "2.13-2.14"

["0.9"]
OrdinaryDiffEq = "2.15-2.18"

["0.10"]
DiffEqBase = "1.21-1.24"
OrdinaryDiffEq = "2.17-2.18"

["1.0"]
DiffEqBase = "1.23-1.24"
OrdinaryDiffEq = "2.19"

["1.0-1.12"]
NLsolve = "0.1-0.13"

["1.0-2.0"]
ForwardDiff = "0.0-0.7"
Roots = "0.1-0.5"

["1.1-1.2"]
OrdinaryDiffEq = "2.21-2.22"

["1.1-1.8"]
DiffEqBase = "2.0-2.10"

["1.3"]
OrdinaryDiffEq = "2.22-2.23"

["1.4-1.7"]
OrdinaryDiffEq = "2.24-2.29"

["1.7-1.12"]
DiffEqDiffTools = "0.2"

["1.8"]
OrdinaryDiffEq = "2.31-2.34"

["1.9-1.10"]
OrdinaryDiffEq = "2.31-2.35"

["1.9-1.12"]
DiffEqBase = "2.8-2.10"

["1.11"]
OrdinaryDiffEq = "2.35"

["1.12"]
OrdinaryDiffEq = "2.36-2.37"

["2.0"]
DiffEqBase = "3.0.3-3.0.4"
DiffEqDiffTools = "0.3"
NLSolversBase = "4.2"
OrdinaryDiffEq = "3.0"
