["0.0"]
julia = "0.4"
LightGraphs = "0.1-0.11"

["0.0-0.2"]
JuMP = "0.13.2-0.18"

["0.0.3"]
GraphMatrices = "0.0-0.1"

["0.1"]
julia = "0.5-0.7"
BlossomV = "0.1-0.3"
Clustering = "0.2-0.9"
LightGraphs = "0.7.2-0.11"

["0.1-0.2"]
MatrixDepot = "0.0-0.5"

["0.2"]
julia = "0.6-0.7"
GLPKMathProgInterface = "0.3.2-0.3.4"
LightGraphs = "0.9-0.11"
