["0.0"]
julia = "0.2-0.7"

["0.0-2.2"]
Requests = "0.0-0.5"

["0.0-3.1"]
HttpCommon = "0.0-0.3"
JSON = "0.1-0.16"

["0.0.5-2.1"]
Dates = "0.0-0.4"

["1.0"]
julia = "0.3-0.7"
Compat = "0.0-0.49"

["2.0-2.1"]
julia = "0.4-0.7"

["2.0-2.2"]
HttpServer = "0.0-0.2"

["2.0-3.1"]
MbedTLS = "0.1-0.5"

["2.1"]
Compat = "0.8.4-0.49"

["2.2"]
julia = "0.5-0.7"
Compat = "0.17-0.49"

["3.0-3.1"]
julia = "0.6-0.7"
HTTP = "0.5.4-0.6"
