["0.1-0.2"]
DeferredFutures = "0.3-0.5"
Iterators = "0.2-0.3"

["0.1-0.3"]
julia = "0.5-0.6"
AutoHashEquals = "0.0.10-0.2"

["0.1-0.4"]
DataStructures = "0.5-0.7"
LightGraphs = "0.7-0.11"
ResultTypes = "0.1-1.1"

["0.1-0.4.0"]
Memento = "0.1-0.5"

["0.3"]
Compat = "0.18-0.49"

["0.3-0.4"]
DeferredFutures = "0.5"
IterTools = "0.1-0.2"

["0.4"]
julia = "0.6-0.7"
AutoHashEquals = "0.1.2-0.2"
Compat = "0.30-0.49"

["0.4.1"]
Memento = "0.3.2-0.5"

["0.4.2"]
Memento = "0.5"
