["0.0"]
DataFrames = "0.10"
DiffEqBase = "0.0-2.10"
DifferentialEquations = "3.0-4.0"

["0.0-0.1"]
julia = "0.6-0.7"
SymEngine = "0.2-0.3"

["0.1"]
DiffEqBase = "2.4-2.10"
LaTeXStrings = "0.3"
Missings = "0.2.2-0.2.5"
