name: Generate and Deploy Redirects

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install Julia
    - name: Install Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: '1'

    # Run the Julia script
    - name: Run Julia script
      run: julia generate_redirects.jl

    - name: Upload static files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: packages/

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
