["0.1-0.4"]
julia = "0.6-0.7"
ForwardDiff = "0.5-0.7"
IterTools = "0.1-0.2"
LsqFit = "0.0-0.3"
NearestNeighbors = "0.0-0.3"
OrdinaryDiffEq = "2.17-2.37"
Requires = "0.4.3"
StaticArrays = "0.5-0.6"
StatsBase = "0.8.2-0.19"

["0.4"]
DiffEqCallbacks = "0.0-1.0"
